name: twilio_programmable_video
description: Flutter plugin for Twilio Programmable Video, which enables you to build
  real-time videocall applications (WebRTC)
version: 0.12.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
twilio_programmable_video:
  path: programmable_video
twilio_programmable_video_platform_interface:
  path: programmable_video_platform_interface
